"""empty message

Revision ID: 0a7229d1c093
Revises: b2a45b99617a
Create Date: 2017-03-24 23:28:07.025357

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a7229d1c093'
down_revision = 'b2a45b99617a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=200), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
