"""added specialty to user db

Revision ID: 507509692148
Revises: 5ca9fa4a6462
Create Date: 2017-03-26 19:52:41.404536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507509692148'
down_revision = '5ca9fa4a6462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('specialty', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'specialty')
    # ### end Alembic commands ###
