"""added tags for entries

Revision ID: 5ca9fa4a6462
Revises: 9c7e666d8316
Create Date: 2017-03-26 19:46:44.788547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ca9fa4a6462'
down_revision = '9c7e666d8316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('tags', sa.String(1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'tags')
    # ### end Alembic commands ###
