"""added num_user_saves as a column

Revision ID: 9c7e666d8316
Revises: 0a7229d1c093
Create Date: 2017-03-26 16:16:29.399176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c7e666d8316'
down_revision = '0a7229d1c093'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('num_user_saves', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'num_user_saves')
    # ### end Alembic commands ###
