"""added specialty and profession

Revision ID: f71df27ace1c
Revises: 507509692148
Create Date: 2017-03-26 21:04:42.088425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f71df27ace1c'
down_revision = '507509692148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profession', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profession')
    # ### end Alembic commands ###
