runtime: python
env: flex
entrypoint: gunicorn -b :$PORT app.app:app

runtime_config:
  python_version: 3

#[START env]
env_variables:
    # Replace user, password, database, and instance connection name with the values obtained
    # when configuring your Cloud SQL instance.
    ENV: prod
#[END env]

#[START cloudsql_settings]
# Replace project and instance with the values obtained  when configuring your
# Cloud SQL instance.
beta_settings:
    # update this with your instance
    cloud_sql_instances: smartphrase-app:us-central1:smartphrase-app
#[END cloudsql_settings]
